version: '3.8'

services:
  vacs:
    container_name: 'pressure-mon'
    image: 'ghcr.io/lnls-sirius/pressure-mon:1.0.3'
    build:
      context: .
    ports:
      - 80:80

  vacs-latest:
    container_name: 'pressure-mon'
    image: 'ghcr.io/lnls-sirius/pressure-mon'
    build:
      context: .
    ports:
      - 80:80
