version: '3.8'

services:
  vacs:
    container_name: 'pressure-mon'
    image: 'ghcr.io/lnls-sirius/pressure-mon:1.1.0'
    volumes:
      - "./pressure-mon:rw"
    build:
      context: .
    ports:
      - 80:80

  vacs-latest:
    container_name: 'pressure-mon'
    image: 'ghcr.io/lnls-sirius/pressure-mon'
    volumes:
      - "./pressure-mon:rw"
    build:
      context: .
    ports:
      - 80:80
